server:
  port: 9001

spring:
  application:
    name: cloud-consumer-orderconsul
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}