server:
  port: 9001


spring:
  application:
    name: cloud-consumer-openfegin-order

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    com.sonia.springcloud.service.PaymentOpenFeignService: debug